services:
#    lcv_core.example:
#        class: LCV\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    lcv_core.doctrine.news_creation:
        class: LCV\CoreBundle\DoctrineListener\NewsCreator
        arguments: []
        tags:
            - { name: doctrine.event_listener, event: postPersist}
            
