lcv_comment_homepage:
    path:     /hello/{name}
    defaults: { _controller: LCVCommentBundle:Default:index }

lcv_comment_view_article:
    path:     /show_comment_article/{article_id}
    defaults: { _controller: LCVCommentBundle:Comment:viewArticle }
    requirements:
        article_id: \d+
        
lcv_comment_view_playlist:
    path:     /show_comment_playlist/{playlist_id}
    defaults: { _controller: LCVCommentBundle:Comment:viewPlaylist }
    requirements:
        article_id: \d+
        
lcv_comment_write:
    path:     /write_comment/{article_id}
    defaults: { _controller: LCVCommentBundle:Comment:write }
    requirements:
        article_id: \d+

lcv_comment_delete:
    path:     /delete_comment/{comment_id}
    defaults: { _controller: LCVCommentBundle:Comment:delete }
    requirements:
        comment_id: \d+
        
lcv_comment_edit:
    path:     /edit_comment
    defaults: { _controller: LCVCommentBundle:Comment:edit }

