<?php

namespace LCV\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function getNews(){
		$query = $this->createQueryBuilder('n')
		->join('n.content','c')
		->addSelect('c')
    	->orderBy('c.date','DESC')
    	->getQuery();
    
    	return $query->getResult();
	}
	
}
