lcv_playlist:
    resource: "@LCVPlaylistBundle/Resources/config/routing.yml"
    prefix:   /playlist

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console

lcv_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix:   /profile

lcv_comment:
    resource: "@LCVCommentBundle/Resources/config/routing.yml"
    prefix:   /

lcv_core:
    resource: "@LCVCoreBundle/Resources/config/routing.yml"
    prefix:   /

lcv_platform:
    resource: "@LCVPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
     
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

_sonata_admin:
    resource:   .
    type:       sonata_admin
    prefix:     /admin
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
 
oneup_uploader:
    resource: .
    type: uploader
 
 
# error-prevention
homepage:
    pattern: /