# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
            
    sonata_user.profile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_sonata_user_profile }
            
    sonata_user.form.handler.profile:
        class: Application\Sonata\UserBundle\Form\Handler\ProfileFormHandler
        arguments: ["@sonata.user.profile.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false
        
    sonata_media.twig.mediaUrlExtension:
        class: Application\Sonata\MediaBundle\Twig\MediaUrlExtension
        tags:
            - { name: twig.extension }
