<?php

namespace LCV\PlaylistBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * AudioCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioCategoryRepository extends NestedTreeRepository
{
    
    
   public function findRootCategory(){
        $query = $this->createQueryBuilder('c')
        ->leftJoin('c.audios','a')
        ->addSelect('a')
        ->orderBy('c.id','ASC')
        
        ->getQuery();
    
         $result=$query->getResult();
         return $result[0];
    }
    
}
