<?php

namespace LCV\PlaylistBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends EntityRepository {
    
    public function getLastPlaylists($limite) {
        $qb = $this -> createQueryBuilder('p') 
            -> orderBy('p.date', 'DESC') 
            -> setMaxResults($limite);

        return $qb -> getQuery() -> getResult();
    }

    public function getOneByIdInOrder($id) {
        $qb = $this -> createQueryBuilder('p')
            -> where('p.id = :id') 
            ->setParameter('id', $id)
            ->leftJoin('p.playlist_audios','a')
            ->addSelect('a')
            ->orderBy('a.sortOrder', 'ASC') ;
        return $qb -> getQuery() -> getResult()[0];
    }
}
