<?php

namespace LCV\PlaylistBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AudioFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistAudioRepository extends EntityRepository
{

   public function getAudioFileList($playlist_id){
        $query = $this->createQueryBuilder('pa')
        ->leftJoin('pa.playlist','p')
        ->where('p.id = :playlist_id')
        ->setParameter('playlist_id',$playlist_id)
        
        ->leftJoin('pa.audio','a')
        ->addSelect('a')
        
        ->orderBy('pa.sortOrder','ASC')
        ->getQuery();
    
        return $query->getResult();
    }

    
}

