<?php

namespace LCV\PlaylistBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaylistCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistCategoryRepository extends EntityRepository
{
}
