<?php

namespace LCV\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
     public function getComments(){
           $query = $this->createQueryBuilder('c')
            ->orderBy('c.date','DESC')
            ->getQuery();
        
            return $query->getResult();
    }
        
      public function getArticleComments($article_id){
           $query = $this->createQueryBuilder('c')
            ->leftJoin('c.article','a')
            ->where('a.id = :article_id')
            ->setParameter('article_id', $article_id)
            ->orderBy('c.date','DESC')
            ->getQuery();
        
            return $query->getResult();
        }
      
     public function getPlaylistComments($playlist_id){
           $query = $this->createQueryBuilder('c')
            ->leftJoin('c.playlist','p')
            ->where('p.id = :playlist_id')
            ->setParameter('playlist_id', $playlist_id)
            ->orderBy('c.date','DESC')
            ->getQuery();
        
            return $query->getResult();
        }
}
