services:
#    lcv_platform.example:
#        class: LCV\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    lcv_platform.beta.html:
        class: LCV\PlatformBundle\Beta\BetaHTML
        
    lcv_platform.beta.listener:
        class: LCV\PlatformBundle\Beta\BetaListener
        arguments: [@lcv_platform.beta.html, "2015-09-30"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
