# app/config/config.yml
parameters:
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin
    
services:
    sonata.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Utilisateurs" }
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [LCVCoreBundle]]
            