services:
    activity_listener:
        class: Application\Sonata\UserBundle\DoctrineListener\ActivityListener
        arguments: [@security.context, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
            
    app.form.registration:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: "form.type", alias: "app_user_registration" }

    app.form.invitation:
        class: Application\Sonata\UserBundle\Form\Type\InvitationFormType
        arguments: ['@app.form.data_transformer.invitation']
        tags:
            - { name: "form.type", alias: "app_invitation_type" }

    app.form.data_transformer.invitation:
        class: Application\Sonata\UserBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: ['@doctrine.orm.entity_manager']
        public: false